version: "3.8"
services:
  frontend:
    container_name: hanlabel-fe
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV}
    image: hanlabel-fe
    restart: always
    ports:
      - "8080:80"
