version: "3.8"
services:
  frontend:
    container_name: notarget-pos-fe
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV}
    image: notarget-pos-fe
    restart: always
    ports:
      - "4300:80"
