export enum DataType {
  INTEGER = "INTEGER",
  LONG = "LONG",
  DOUBLE = "DOUBLE",
  STRING = "STRING",
  LONG_STRING = "LONG_STRING",
  DATETIME = "DATETIME",
  BOOLEAN = "BOOLEAN",
  RELATION = "RELATION",
  IMAGE = "IMAGE",
  AUDIT = "AUDIT",
  ENUM = "ENUM",
}
