/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/base/AppFooter.vue')['default']
    AppHeader: typeof import('./components/base/AppHeader.vue')['default']
    ConfirmPopup: typeof import('./components/shared/ConfirmPopup.vue')['default']
    CustomerPage: typeof import('./components/customer/CustomerPage.vue')['default']
    CustomListMenu: typeof import('./components/shared/CustomListMenu.vue')['default']
    EmployeePage: typeof import('./components/employee/EmployeePage.vue')['default']
    EnumInput: typeof import('./components/shared/EnumInput.vue')['default']
    FloatNumberInput: typeof import('./components/shared/FloatNumberInput.vue')['default']
    Form: typeof import('./components/shared/Form.vue')['default']
    HomePage: typeof import('./components/home/HomePage.vue')['default']
    ImportExcelPopup: typeof import('./components/shared/ImportExcelPopup.vue')['default']
    IntegerNumberInput: typeof import('./components/shared/IntegerNumberInput.vue')['default']
    PaymentSuccessPopup: typeof import('./components/sell/PaymentSuccessPopup.vue')['default']
    ProductListPage: typeof import('./components/product/list/ProductListPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SellInfo: typeof import('./components/sell/SellInfo.vue')['default']
    SellInfoInput: typeof import('./components/sell/SellInfoInput.vue')['default']
    SellInfoSelect: typeof import('./components/sell/SellInfoSelect.vue')['default']
    SellPage: typeof import('./components/sell/SellPage.vue')['default']
    SellSearchInput: typeof import('./components/sell/SellSearchInput.vue')['default']
    Table: typeof import('./components/shared/Table.vue')['default']
    TextInput: typeof import('./components/shared/TextInput.vue')['default']
  }
}
