/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/base/AppFooter.vue')['default']
    AppHeader: typeof import('./components/base/AppHeader.vue')['default']
    CustomListMenu: typeof import('./components/shared/CustomListMenu.vue')['default']
    FloatNumberInput: typeof import('./components/shared/FloatNumberInput.vue')['default']
    Home: typeof import('./components/home/Home.vue')['default']
    HomePage: typeof import('./components/home/HomePage.vue')['default']
    IntegerNumberInput: typeof import('./components/shared/IntegerNumberInput.vue')['default']
    ProductListPage: typeof import('./components/product/list/ProductListPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sell: typeof import('./components/sell/Sell.vue')['default']
    SellInfo: typeof import('./components/sell/SellInfo.vue')['default']
    SellInfoInput: typeof import('./components/sell/SellInfoInput.vue')['default']
    SellInfoSelect: typeof import('./components/sell/SellInfoSelect.vue')['default']
    SellPage: typeof import('./components/sell/SellPage.vue')['default']
    SellSearchInput: typeof import('./components/sell/SellSearchInput.vue')['default']
    Table: typeof import('./components/shared/Table.vue')['default']
  }
}
